### ISSUE TITLE
[0.16] use std::time::Duration instead of time::Duration

### ISSUE THREAD

**Issue by jhgg** [Metaswitch/cassandra-rs#102]
Don't entirely know why this decision was made, but after an audit of the call-sites, it would appear that the std duration would be more than acceptable, and we can drop this extra dependency.

My hunch is that the necessary methods with std's duration were not added until rust v1.33, https://doc.rust-lang.org/std/time/struct.Duration.html#method.as_millis

our msrv is at-least 1.39 so this should be :+1:

**Comment by kw217** [comment]
Agree, let's fix this to use std's `Duration`. (In any case we should use `chrono` in favour of `time` - but if we can avoid both that's even better).
