### ISSUE TITLE
[0.16] rename `CassCollection::new` -> `CassCollection::with_capacity`

### ISSUE THREAD

**Issue by jhgg** [Metaswitch/cassandra-rs#105]
The size passed to `CassCollection::new(...)` is but a hint to avoid re-allocations, very similar to how the similarly named `Vec` methods work. 

This issue proposes re-naming it to `with_capacity`, and providing a `new` that just calls `with_capacity(0)`. This will clarify intent for users of the library that the size is but a hint/optimization. 

The underlying ffi we're wrapping is here: https://docs.datastax.com/en/developer/cpp-driver/2.4/api/struct.CassCollection/#function-cass_collection_new - the docs mention it as an "approximate count" - and reading into the source code of where it's eventually used, https://github.com/datastax/cpp-driver/blob/master/src/collection.hpp#L42 we can see it's just pre-sizing an array as well to avoid re-allocations.

**Comment by kw217** [comment]
Sounds good.
