### ISSUE TITLE
Expose Astra authentication

### ISSUE THREAD

**Issue by pkolaczk** [Metaswitch/cassandra-rs#111]
The underlying C++ driver offers a function `cass_cluster_set_cloud_secure_connection_bundle` to authenticate using a bundle from Astra (cloud hosted cassandra) since version 2.14.

Can you expose that functionality in the bindings?
That small addition would increase applicability of the bindings. No other Rust driver has this functionality at the moment.

Relevant documentation: 
https://docs.datastax.com/en/developer/cpp-driver/2.15/topics/cloud/

Thank you.

**Comment by kw217** [comment]
Thanks - certainly happy to accept a PR!

First cassandra-sys-rs needs to be updated to the latest, like this previous PR: https://github.com/Metaswitch/cassandra-sys-rs/pull/18/files . And then the new binding would need to be exposed in https://github.com/Metaswitch/cassandra-rs/blob/master/src/cassandra/cluster.rs .

Thanks for the report.

**Comment by alexeiakimov** [comment]
Hi there, I am interested in AstraDB support too. @kw217 could you please provide more information about updating the cassandra-sys library? According to the PR https://github.com/Metaswitch/cassandra-sys-rs/pull/18/files mentioned above it seems enough 

1. to update cassandra.h from the lates driver
2. to regenerate the binding code with bindgen utility
3. to update the changelog
4. to update the travis descriptior to download the correct driver library

At the same time the cassandra-sys project

1. has examples which probably should be updated as well
2. can have some special requirements like code formatting, testing, etc

It would be nice to have more information about the requirements which a PR should meet. Thank you.

**Comment by kw217** [comment]
Hi @alexeiakimov - yes, that's the right process. I've written up some more detailed notes at https://github.com/Metaswitch/cassandra-sys-rs/issues/38. Thanks!

**Comment by kw217** [comment]
Implemented by #132 .
