### ISSUE TITLE
Make execute_batch not consume its argument

### ISSUE THREAD

**Issue by kw217** [Metaswitch/cassandra-rs#118]
We're implementing some retry logic at the moment, and we've hit a challenge that I think is caused by a simple oversight in the binding. `execute_batch` is declared as follows (https://github.com/Metaswitch/cassandra-rs/blob/master/src/cassandra/session.rs#L129):
```rust
pub fn execute_batch(&self, batch: Batch) -> CassFuture<CassResult>
```
i.e., it consumes `Batch`. There is nothing in either its implementation or in the C++ docs at https://docs.datastax.com/en/developer/cpp-driver/2.16/api/struct.CassSession/#function-cass_session_execute_batch that suggests this should be the case, and `execute` doesn't consume its `Statement`. So I think this is just a mistake. Similarly for `execute_batch_with_payload`.

Does anyone have any objections to me making this change? It would be a breaking API change, but a very easy one to fix (just add `&` at the callsite).

**Comment by jhgg** [comment]
I think that passing by reference might have triggered some odd lifetime woes across cffi bounds. I don't remember specifically, but might as well try it and see.
