### ISSUE TITLE
Clean up clippy warnings

### ISSUE THREAD

**Issue by dimbleby** [Metaswitch/cassandra-rs#33]
As noted [here](https://github.com/Metaswitch/cassandra-rs/pull/32#issuecomment-350549112), mostly clippy complains about functions unnecessarily consuming their parameters - of which there are rather a lot of examples.

But that's not all.  WIBNI to clean up generally...

**Comment by kw217** [comment]
Closing - stale. We seem to be coping without this cleanup, though I admit it would be nice.
