### ISSUE TITLE
Every _CassResult is leaked by CassResult

### ISSUE THREAD

**Issue by CorbinH** [Metaswitch/cassandra-rs#35]
The Drop trait for CassResult was commented out to work around an issue with bind_by_name apparently causing double-frees.

See [the commented out code here](https://github.com/Metaswitch/cassandra-rs/blob/58ab265e4bcd0831ebfb6d897938881bf391d0b6/src/cassandra/result.rs#L70-L75)

**Comment by kw217** [comment]
Thanks @CorbinH - unfortunately there are a number of leaks like this. We intend to beef up the test suite and start addressing them at some point, but at the moment we're focussing on fixing functional and API issues. We'd happily accept a PR if you want to have a go - see [CONTRIBUTING.md](https://github.com/Metaswitch/cassandra-rs/blob/master/CONTRIBUTING.md).

The existing `bind_by_name` tests are in https://github.com/Metaswitch/cassandra-rs/blob/master/tests/bind_by_name.rs but you might need to extend them to be confident the issues are properly fixed. I'm happy to review your code and help you diagnose any issues.
