### ISSUE TITLE
Create cassandra_cpp::Uuid from uuid::Uuid

### ISSUE THREAD

**Issue by kadfak** [Metaswitch/cassandra-rs#56]
I'm wondering if there is a better way to convert an [`uuid::Uuid`](https://docs.rs/uuid/0.7.1/uuid/struct.Uuid.html) into `cassandra_cpp::Uuid`.

Currently I'm converting the `uuid::Uuid` into a string and then into `cassandra_cpp::Uuid`. I think the string conversion is an unnecessary intermediary step.

Am I missing something?

**Comment by kw217** [comment]
Thanks for the feedback! Unfortunately the DataStax Cassandra driver has its own UUID type, and it is only interconvertible with strings - see https://docs.datastax.com/en/developer/cpp-driver/2.11/api/struct.CassUuid/ . So this is unavoidable.

It would be nice if this library did the conversion automatically - I'd be happy to accept a pull request adding this: adding `impl AsRustType<uuid::Uuid> for Row` in row.rs and `impl BindRustType<uuid:Uuid> for Statement` in statement.rs.
