### ISSUE TITLE
Can I use the known uuid as the primary key?

### ISSUE THREAD

**Issue by pili2026** [Metaswitch/cassandra-rs#57]
Excuse me, can I use the known uuid as the primary key? And used to make a query?

**Comment by kw217** [comment]
Sorry, please can you clarify your question?

**Comment by pili2026** [comment]
I mainly want to use uuid as the key of the query. 
At first I used the uuid type as the property of the argument. 
However, it failed, but in the end I found that just adding single quotation marks (' ') to the input key would solve.
So, this becomes a stupid question, sorry.

**Comment by kw217** [comment]
No problem! I'm pleased you resolved your issue.
