### ISSUE TITLE
Bind a vector/array for IN Keyword

### ISSUE THREAD

**Issue by z-rudyar** [Metaswitch/cassandra-rs#60]
Hello,

I'm using the ` IN ?` keyword on a clustering key to filter out results 
https://docs.datastax.com/en/archived/cql/3.3/cql/cql_using/useQueryIN.html

Unfortunately, I'm not able to bind a vector or array to my query to fill the IN ? part of the query

Is there an alternative way to do it? 

Thanks!

**Comment by kw217** [comment]
I think you're looking for `bind_list` https://docs.rs/cassandra-cpp/0.14.0/cassandra_cpp/struct.Statement.html#method.bind_list . Apologies for delay in response!

**Comment by z-rudyar** [comment]
Thanks for your help!
