### ISSUE TITLE
Migrating to futures 0.3

### ISSUE THREAD

**Issue by sntdevco** [Metaswitch/cassandra-rs#63]
With async/await rolling out into the entire ecosystem, it's time to upgrade existing code to the latest future and to use `std::future`, as that has been stabilized too. I can help out in this too (I have some good amount of free time next weekend)

**Comment by kw217** [comment]
Thanks - a PR for this would be very welcome indeed! Note that there is some tricky code in here, to convert the C library's own futures into Rust futures.
