### ISSUE TITLE
How to store pagination token?

### ISSUE THREAD

**Issue by sntdevco** [Metaswitch/cassandra-rs#64]
I want to store a copy of the pagination token. How can I achieve this?

**Comment by bnjjj** [comment]
Did you find a solution ?

**Comment by sntdevco** [comment]
> Did you find a solution ?

None as of now. But I found out that exposing a pagination token may not be very safe (as in my case).

**Comment by kw217** [comment]
Hi - @sntdevco closed this issue so I haven't commented on it. But you may find you can achieve the same effect by saving the primary key of the last record, and doing a search for `token(key) >= XX`.
