### ISSUE TITLE
Fails to compile on macOS due to stdc++ library ref

### ISSUE THREAD

**Issue by a1ph** [Metaswitch/cassandra-rs#68]
The following line in build.rs causes the problem:
    println!("cargo:rustc-flags=-l dylib=stdc++");

          ld: library not found for -lstdc++
          clang: error: linker command failed with exit code 1 (use -v to see invocation)

Can you please disable it, at least for macOS builds? Thanks.

**Comment by jhgg** [comment]
I believe this was fixed here: https://github.com/Metaswitch/cassandra-sys-rs/pull/24

May just need to update cassandra-sys-rs dependency.

**Comment by kw217** [comment]
Thanks @jhgg . @a1ph - please can you comment whether this fixed your problem?

**Comment by a1ph** [comment]
It did not.
The library comes not from cassandra-sys-rs but from cassandra-rs build.rs file. See https://github.com/Metaswitch/cassandra-rs/blob/master/build.rs#L11

Actually I believe you don't need build.rs file at all in cassandra-rs. It does not directly depend on these libraries, cassandra-sys-rs does and brings them transitively.

**Comment by kw217** [comment]
Thanks @a1ph . Any chance you could put together a PR to remove this file, or otherwise resolve your build issue? (please note the details about signoff in https://github.com/Metaswitch/cassandra-rs/blob/master/CONTRIBUTING.md ). Thanks!

**Comment by kw217** [comment]
This should now be fixed by #71 . Thanks all!

**Comment by pnehrer** [comment]
Thank you!
