### ISSUE TITLE
Convert to owned repository

### ISSUE THREAD

**Issue by nkconnor** [Metaswitch/cassandra-rs#69]
being forked doesn't allow code search on GitHub which is very convenient. is it possible to convert this fork to a first-class repository?

also have you contacted the original author @tupshin about transfering the repo? that repo still shows up first in Google search from what I've seen

**Comment by kw217** [comment]
I would like to convert it to an owned repository, but that's not something I can do from the UI. I will see if I can request GitHub to do this.

I have contacted @tupshin many times and they have been completely unresponsive - see e.g., https://github.com/tupshin/cassandra-rs/issues/52. The Rust team have also attemped to contact them without success.

**Comment by kw217** [comment]
I've sent a request to GitHub support.

**Comment by kw217** [comment]
This appears to have been done! (although I haven't received confirmation from GitHub).

Sadly I forgot to ask for the same re cassandra-sys-rs. I've asked them now.

**Comment by kw217** [comment]
That's done too now. Thanks for the prompt.
