### ISSUE TITLE
Allow PreparedStatement to be used across threads

### ISSUE THREAD

**Issue by kalabukdima** [Metaswitch/cassandra-rs#72]
`PreparedStatement` implements neither `Sync` nor `Clone`, which makes it impossible to use single prepared statement across multiple threads with the following error:
```
`*const cassandra_cpp_sys::cassandra::CassPrepared_` cannot be shared between threads safely
...
note: required because it appears within the type `cassandra_cpp::PreparedStatement`
```

From [datastax docs](http://datastax.github.io/cpp-driver/api/struct.CassPrepared/):
> A prepared statement is read-only and it is thread-safe to concurrently bind new statements.

which makes me think that `PreparedStatement` not implementing `Sync` is just a mistake.

If I'm wrong, could you please provide an example of how `PreparedStatement`s are expected to be used?

**Comment by kw217** [comment]
The Rust code contains the following comment on `PreparedStatement`:
```rust
// The underlying C type has no thread-local state, but does not support access
// from multiple threads: https://datastax.github.io/cpp-driver/topics/#thread-safety
```
Accordingly, it implements `Send` but not `Sync`.

That means you can get what you want by wrapping it in a `Mutex` - the mutex will ensure it's only ever used by one thread at a time.

HTH.

**Comment by kalabukdima** [comment]
I believe that the "Thread safety" docs section only refers to concepts mentioned in the "Getting started" page. Shouldn't [API docs](http://datastax.github.io/cpp-driver/api/struct.CassPrepared/) be given preference in case of contradiction like this?
I don't see a reason why read-only access from multiple threads has to be synchronized. It seems like a performance issue if all `bind` calls have to be made under a global lock.

Could you please consider revisiting this issue?

**Comment by kw217** [comment]
You're right, the API doc you've linked is more specific than the general one the original author linked in the comment. Thanks for pointing that out.

It's hard to imagine this being a performance issue - the act of binding doesn't take very long at all. But I'm now happy to accept a PR fixing this. Thanks!
